Trans(docs/*/latest/tutorial/_data.json)
angular/angular-ko pull request #23
Opened 2017-01-10 15:15 UTC by onyoon7

- Trans(docs/ts/latest/tutorial/_data.json)
- Trans(docs/js/latest/tutorial/_data.json)

2017-01-11 12:16 UTC, onyoon7 commented
@tiratano 시간되실 때 리뷰 한 번 부탁드리겠습니다 : )

2017-01-11 16:50 UTC, tiratano requested changes
js와 ts에 같은 내용은 먼저 확인한 js에만 적었습니다.
몇가지 질문이 포함되어 있기는 한데 Request changes 하면 되는건가요?

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> +    "title": "양식",
Input과 비슷한 맥락에서 고민했는데요,
국내 출시 도서들을 보니 "폼" 이라고 발음을 그대로 쓴 경우가 많고 많이 쓰이는 키워드이므로 
그냥 "폼" 이라고 하는 것도 좋을 것 같습니다.

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> -    "title": "User Input",
Input 같은 영어단어 관련해서 제가 번역 했던걸 보니
- deep link는 영어 그대로 (딱 한번 나오는 영어라서)
- 자주 나오는 주요 키워드인 hero, element, template, component, method, part, chapter, target(타겟), event 같은 것은 영어를 한글 발음으로 했었습니다. (한글 발음으로 한게 많네요!)

특히 input은 "인풋" 이라고 했었는데.. 
input 태그나, @Input 처럼 키워드가 아닌 경우는 "입력" 이라고 번역을 해주는게 좋을 것 같습니다.
이 부분은 제가 "입력"으로 바꾸겠습니다.

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> +    "title": "라이프사이클 후크",
저는 "훅" 이라고 표기해서 찾아봤는데..
http://krdic.naver.com/search.nhn?kind=study&query=%ED%9B%85
hook의 외래어표기법은 "훅" 인 것 같습니다. 

개발 번역시는 보통 어떻게 하는지 잘 모르겠네요..
혹시 제가 고쳐야 하면 알려주세요. :)

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> +    "title": "구조 지시문",
structural directives가 ngSwitch, ngIf, ngFor 같은 내장 지시자로
문장의 느낌보다 단어의 느낌이 많으니까 "지시자"라고 하면 좋을 것 같습니다.

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> +    "intro": "Angular app을 테스트하기 위한 기법과 절차",
저는 app을 "앱"이라고 쓰고 있어서요, 통일성을 위해 표기방법 의견 부탁 드립니다. :)

2017-01-11 16:50 UTC, tiratano commented on public/docs/js/latest/guide/_data.json
> +    "title": "TypeScript 구성",
앗.. configuration을 보통 설정이라고 했는데 구성이라는 표현도 많이 쓰시는 군요.
제가 "구성"으로 변경하겠습니다.

2017-01-11 16:50 UTC, tiratano commented on public/docs/ts/latest/guide/_data.json
> +    "title": "AppModule: 루트 모듈",
root도 "최상위"라고 할지 고민했었는데 루트라고 하셨군요.
제가 "루트" 라고 고치겠습니다.

2017-01-12 00:54 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> -    "title": "User Input",
👍

2017-01-12 00:54 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> +    "title": "양식",
리뷰해주신 내용 수정/반영하도록 하겠습니다.

- 변경전 : 양식
- 변경후 : 폼

2017-01-12 00:55 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> +    "title": "라이프사이클 후크",
리뷰해주신 내용 수정/반영하도록 하겠습니다.

- 변경전 : 라이프사이클 후크
- 변경후 : 라이프사이클 훅

2017-01-12 00:55 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> +    "title": "구조 지시문",
저도 보통 지시자라고 번역하였는데 해당 부분 리뷰해주신 내용 수정/반영하도록 하겠습니다.

- 변경전 : 지시문
- 변경후 : 지시자

2017-01-12 00:55 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> +    "intro": "Angular app을 테스트하기 위한 기법과 절차",
저도 동의합니다. 제가 실수한 부분이네요.
리뷰해주신 내용 수정/반영하도록 하겠습니다.

- 변경전 : App
- 변경후 : 앱

2017-01-12 00:55 UTC, onyoon7 commented on public/docs/js/latest/guide/_data.json
> +    "title": "TypeScript 구성",
문맥상 '구성'보다 '설정'이 더 잘 어울릴것 같습니다.
리뷰해주신 내용 수정/반영하도록 하겠습니다.

#### configuration 번역
- 변경전 : 구성
- 변경후 : 설정

2017-01-12 00:55 UTC, onyoon7 commented on public/docs/ts/latest/guide/_data.json
> +    "title": "AppModule: 루트 모듈",
문맥상 '루트'보다 '최상위'가 더 잘 어울릴것 같습니다.
영어보다는 그에 맞는 한글로 번역하는 것이 좋기도 하고요.
리뷰해주신 내용 수정/반영하도록 하겠습니다.

#### root 번역
- 변경전 : 루트
- 변경후 : 최상위

2017-01-13 13:10 UTC, tiratano approved these changes

2017-01-13 14:04 UTC, tiratano commented
@onyoon7 코멘트 확인하여 approved 처리 했습니다. 커밋 부탁드립니다. :)

2017-01-13 15:56 UTC, tiratano reviewed
앗 public/docs/js/latest/guide/_data.json 
130줄에 구조 지시자에서 "자"가 빠진 것 같네요.

2017-01-13 16:33 UTC, merged