Trans(ts/guide 4,5,6)
angular/angular-ko pull request #27
Opened 2017-01-16 13:19 UTC by onyoon7

- Trans(public/docs/ts/latest/guide/appmodule.jade)
- Trans(public/docs/ts/latest/guide/architecture.jade)
- Trans(public/docs/ts/latest/guide/displaying-data.jade)
- Fix some syntax and words

2017-01-17 16:10 UTC, tiratano requested changes
리뷰를 완료했습니다. 검토 부탁 드립니다. : )

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/_data.json
> +    "intro": "최상위 \"AppModule\"에서 앱을 만들고 실행하는 방법을 배워보세요.",
앗 저는 처음에는 "시작", "실행" 처럼 하다가 glossary.jade를 보고 "부트스트래핑"이라고 했었는데요,
dependency-injection.jade에서도 표현을 고민 중입니다.

명확한 키워드가 아닌 경우는 "실행" 이라고 통일을 하시려는 것이지요?
저도 그럼 키워드가 아닌 경우는 "실행"으로 번역하겠습니다.

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/_data.json
> +    "intro": "최상위 \"AppModule\"에서 앱을 만들고 실행하는 방법을 배워보세요.",
"시작(bootstrap)"으로 하신 부분도 있군요. (architecture.jade)
의미상 혼란이 없으면 실행 or 시작으로, 염려가 되면 영문표기를 괄호에 넣겠습니다.

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +  * [종속성 주입(Dependency injection)](#dependency-injection)
Angular 뿐 아니라 자바 진영의 책에도 "의존성 주입" 이라는 용어로 많이 번역하고 있으므로
"종속성"을 "의존성" 으로 하면 어떨까요? : )

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +    `NgModule`은 모듈을 설명하는 속성을 가진 단일 메타 데이터 객체를 갖는 데코레이터 함수입니다.
metadata가 한 단어로 많이 사용되고 있으므로 "메타 데이터"의 띄어쓰기를 빼고 "메타데이터"로 하면 좋을 것 같습니다.

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +  * 네비게이션 링크가 있는 앱 루트
저도 다른 분이 슬쩍 리뷰해주면서 보통 "내비게이션"으로 많이 쓴다고 해서 놀랐었는데요
http://krdic.naver.com/rescript_detail.nhn?seq=4236
"내비게이션"으로 많이 쓴다고 합니다.. ^^;

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +  예를 들어, `HeroListComponent`는 서비스에서 획득 한 영웅의 배열을 반환하는 `heroes`속성을 가지고 있습니다.
이곳에서만 "영웅"으로 번역되어 "히어로"로 통일을 하면 좋을 것 같습니다.

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +<p style="padding-top:10px">메타 데이터는 Angular가 어떻게 클래스를 처리하지 알려줍니다.</p>
위와 같이 "메타데이터"로 통일하면 좋을 것 같습니다. : )

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +    다음은 '@ Component` 설정 옵션의 몇 가지 예입니다 :
원문과 다르게 '@ Component` 골뱅이와 Component 사이에 띄어쓰기가 포함되어 있습니다.

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/architecture.jade
> +  종속성 주입에 대해 기억해야 할 점 :
Angular 뿐 아니라 자바 진영의 책에도 "의존성 주입" 이라는 용어로 많이 번역하고 있으므로
"종속성"을 "의존성" 으로 하면 어떨까요? : )

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/appmodule.jade
> +  브라우저에서 실행되는 모든 애플리케이션은 `@angle/platform-browser`의 `BrowserModule`이 필요 합니다.
오타가 발견되었습니다. `@angle/platform-browser` => `@angular/platform-browser`

2017-01-17 16:10 UTC, tiratano commented on public/docs/ts/latest/guide/appmodule.jade
> +  모든 Angular 애플리케이션은 최상위 `NgModule`을 가져야하며, 심지어 [빠른시작](../quickstart.html)페이지도 마찬가지이다.
이 문장에서만 존칭이 생략되어 조금 어색한 것 같습니다. ^^;
"마찬가지이다.", "있었다."

2017-01-18 09:44 UTC, onyoon7 commented
@tiratano 리뷰 감사합니다 : )
리뷰해 주신 사항 반영하여 PR하였습니다.
**확인 후 Merge 하도록 하겠습니다.**

2017-01-18 12:08 UTC, tiratano approved these changes
넵 확인했습니다~

2017-01-18 12:10 UTC, merged