Trans(cookbook/form-validation)
angular/angular-ko pull request #50
Opened 2017-03-22 16:16 UTC by grapgrap

늦어서 죄송합니다. 더 분발 하도록 하겠습니다.

2017-03-23 01:51 UTC, grapgrap commented
I signed it.

2017-03-23 17:00 UTC, tiratano requested changes
아직 전체 리뷰는 하지 않았지만 원문과 들여쓰기가 너무 달라서 문장 하나씩 변경 여부를 확인하기가 어렵습니다. 원문과 들여쓰기 일치 후 다시 요청 부탁 드립니다.

2017-03-23 17:00 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> -  We can improve overall data quality by validating user input for accuracy and completeness.
Review시 빨간색이 뜨면 뭔가 원문에서 제거된 것이기 때문에 좀 더 주의 깊게 봐야 하고,
나중에 merge 시에도 한번 더 살펴봐야 하는 어려움이 있습니다.

그리고 jade 문서는 들여쓰기 칸 수가 매우 중요하기 때문에 특별한 사유가 없다면
원문과 들여쓰기 칸 수를 맞춰주시기 바랍니다.

이전: 들여쓰기 4칸
이후: 들여쓰기 2칸 (원문과 동일한 들여쓰기)

2017-03-23 17:00 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> -  In this cookbook we show how to validate user input in the UI and display useful validation messages
여기서 보이는 것처럼 들여쓰기가 동일했다면 
녹색도, 빨간색도 없는 부분이라 리뷰시 그냥 skip 하면 되는 부분인데
들여쓰기가 달라지면 혹시 누락된 것인지, 아니면 다른 부분에 섞여 있는 것인지 찾아보는데 시간이 걸리게 됩니다.

한글 리뷰시는 괜찮은데 영문 merge시에도 또 검토를 하게 되니까요..
꼭 필요한 경우가 아니면 들여쓰기는 반드시 원문과 같게 해주세요~

2017-03-23 17:00 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    **실시간 예제를 실행해보고, 요리책의 소스 코드 전체를 다운로드 할 수 있습니다.**
live example은 "라이브 예제"로 통일하여 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-23 17:00 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    **실시간 예제를 실행해보고, 요리책의 소스 코드 전체를 다운로드 할 수 있습니다.**
동사 원형으로 시작하는 명령문이지만 이런 경우
~하세요 정도의 권유형으로 번역을 하고 있습니다.

이전: 실시간 예제를 실행해보고, 요리책의 소스 코드 전체를 다운로드 할 수 있습니다.
이후: 라이브 예제를 실행하고 전체 요리책의 소스 코드를 다운로드 하세요.

2017-03-23 17:07 UTC, grapgrap commented
ide 들여쓰기설정 때문에 4칸으로 모두 바뀌었나보네요 ㅠㅠ 나머지수정사항까지 반영해서 올리도록 하겠습니다

2017-03-23 17:36 UTC, tiratano requested changes
수고하셨습니다. 👍 그런데 띄어쓰기와 오타, 번역의 이해도 등을 봤을 때 세심하게 한번 더 살펴봐주셔야 할 것 같습니다. 부탁 드립니다. : )

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    우리는 이런 것을 제어모델이 템플릿에 함축되어 있다고 표현 합니다.
"우리는"은 꼭 필요한 부분이 아니면 가급적 번역하지 않고 있습니다. : )
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    우리는 이런 것을 제어모델이 템플릿에 함축되어 있다고 표현 합니다.
표현 합니다. => 표현합니다.

혹시 번역기를 사용하셨다면 띄어쓰기를 꼭 자세히 살펴봐주시기 바랍니다.

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    아래 코드는, 히어로의 이름에 연결된 단일 입력 폼 컨트롤에 대한 html 템플릿의 일부를 발췌한 것입니다.
"아래 코드는" 다음에 쉼표가 갑자기 나타났습니다.

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    추가 정보:
번역이 잘못 된 것 같습니다.. ^^;
이전: 추가 정보
이후: "다음 사항을 유의하세요." or "유의사항"

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    - 입력 박스에 `"name"`이라는 `name` 속성을 부여하므로서, 그것과 연관된 `<input>`를  Angular의 내부 제어 모델에서 `name`이라는 폼 컨트롤과 연결 할 수 있습니다.
"부여하므로서" => "부여함으로써"

~로서:지위.신분.자격을 나타내는 데 쓰이는 격조사
~로써:수단.도구등을 나타내는 데 쓰이는 격조사

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    - `<div>`에 있는 `*ngIf`는 "name"에 오류가 있고 폼 컨트롤이 `dirty`나 `touched`일 때만 `<div>`들에 적혀있는 메시지를 보여줍니다.
element, nested 처럼 원문에 있는 단어의 번역이 누락되었습니다.
특별한 이유가 없거나 한글로 직역하면 어색한 표현이 아니라면 가급적 원문에 가깝게 번역해주세요.

2017-03-23 17:36 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    The full template repeats this kind of layout for each data entry control on the form.
번역이 전혀 다르게 되었습니다....

예제나 엔티티라는 것은 원문에 없는 내용입니다.

2017-03-23 17:42 UTC, grapgrap commented
늦은시간까지 검토 감사합니다. 띄어쓰기외 쉼표는 제 버릇이 저도 모르게 나온것 같습니다. 애매하면쓰고 보자 주의라서요 ㅠㅠ 번역누락은 영어실력이 부족해 번역 후에 어색하다고 느껴서 제외했거나 없어도 되는 단어라고 생각해 누락했습니다만, 최대한 원문에 가깝게 번역하도록 노력하겠습니다. 번역이 아예 틀린 곳은 저도 제가 왜 그랬는지 잘 모르겠네요 ㅠㅠ 전체적으로 미숙한 곳이 많은 것 같습니다. 리뷰 감사합니다

2017-03-29 15:29 UTC, grapgrap commented
나름 꼼꼼히 본다고 봤는데 어떤지 잘 모르겠네요 리뷰 잘 부탁드립니다.

2017-03-29 17:24 UTC, tiratano requested changes
grapgrap님 아직 전체 리뷰를 하지는 못했지만 들여쓰기, 쉼표, 띄어쓰기 등 기초적인 것부터 번역의 일관성이나 품질로 봤을때 수정해야 될 내용이 너무 많은 것이 사실입니다. 아직 번역의 내용은 자세히 살펴보지 못했는데 이렇게 한 글자, 한 글자 리뷰를 해가면서 수정사항을 반영하기에는 리뷰어에게 너무 많은 수고가 필요한 것 같습니다. 죄송하지만 조금 더 연마를 하신 뒤에 다음에 참여해주시면 어떨지 말씀드려봅니다. 이 페이지는 저나 다른 분께 재할당을 하면 될 것 같습니다. 죄송합니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  이번 요리책에서는, 사용자 입력에 대한 유효성 검사를 UI안에서 어떻게 수행하고 의미있는 유효성 검사 메시지를 어떻게 보여줄 수 있는지를 살펴볼 것입니다.
slack으로 논의했던 내용인데요 cookbook을 "요리책"으로 번역하는 것이 어색하여 "쿡북"으로 수정하기로 했습니다.
참고로 recipe "요리법"은 "레시피"로 하기로 했습니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  **라이브 예제를 실행해보고, 요리책의 소스 코드 전체를 다운로드 할 수 있습니다.**
~를 실행해보고, ~를 다운로드 할 수 있습니다. 라는 문장 구조가 좀 어색하고
Try... 문장은 명령문이어서 저번에 코멘트 했던 내용이 있습니다.
https://github.com/angular/angular-ko/pull/50/files/0bfcccff3b357a33dd301dd5f04c855c652b6673

이전: 실시간 예제를 실행해보고, 요리책의 소스 코드 전체를 다운로드 할 수 있습니다.
이후: 라이브 예제를 실행하고 전체 쿡북의 소스 코드를 다운로드 해보세요.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  정확성과 완전성을 위한 사용자 입력에 대한 유효성 검사는 전체적인 데이터 퀄리티의 향상을 가져올 수 있습니다.
by 구문으로 전체 데이터 퀄리티를 높이는 방법에 대해 소개 하는 문장이므로 "~는 ~를 향상시킨다."는 느낌보다는 어떻게 하여 향상시키는지가 나와야 할 것 같습니다.

예: 정확성과 완결성을 위해 사용자 입력의 유효성을 검사하여 전체 데이터 퀄리티를 향상시킬 수 있습니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> -  In this cookbook we show how to validate user input in the UI and display useful validation messages
원문에는 끝에 공백이 있는데 제거되어 빨간색으로 표시가 되고 있습니다.
가급적 원문은 그대로 둔 상태에서 번역 부탁 드립니다.

지금처럼 거의 공백 문제이지만 혹시 모를 문제를 대비해 원문과 확인을 해야 합니다. ㅠ
간혹 이런게 한 두개 있으면 그냥 넘어가는데 여전히 원문에 빨간색이 많이 뜨고 있네요 ㅠ

가장 이상적인 모습은 원문에는 전혀 빨간색이 뜨지 않는 것입니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    `dirty`와 `touched`에 대해 더 알고 싶다면 [폼 챕터](../guide/forms.html)를 참고 합시다.
전체적인 번역의 문체는 하십시오체(=합쇼체)를 기본으로 하고
명령형에 대해서는 하십시오체의 ~하십시오 또는 강제성을 순화하기 위해 해요체의 ~하세요.로 쓰고 있습니다.

"합시다"는 하오체의 청유형으로 전체적인 문체와 달라서 해요체로 수정 부탁 드립니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    그것들은 유효성 검사와는 밀접한 관련이 있지 않습니다. 흥미가 있다면 [라이브 예제](#live-example)를 참고 합시다.
위에 설명한 이유로 "합시다"와 같은 하오체의 청유형은 사용하지 않고 있습니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    폼에 대해 더 알고 싶다면 [폼 챕터](../guide/forms.html)를 참고합시다.
전체적인 번역의 문체는 하십시오체(=합쇼체)를 기본으로 하고
명령형에 대해서는 하십시오체의 ~하십시오 또는 강제성을 순화하기 위해 해요체의 ~하세요.로 쓰고 있습니다.

"합시다"는 하오체의 청유형으로 전체적인 문체와 달라서 해요체로 수정 부탁 드립니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    `dirty`와 `touched`에 대해 더 알고 싶다면 [폼 챕터](../guide/forms.html)를 참고 합시다.
띄어쓰기가 잘못 되었습니다.
"참고 합시다." => "참고하세요."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    그것들은 유효성 검사와는 밀접한 관련이 있지 않습니다. 흥미가 있다면 [라이브 예제](#live-example)를 참고 합시다.
띄어쓰기가 잘못 되었습니다.
"참고 합시다." => "참고하세요."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  * 메시지는 정적인 문자열이고, 템플릿에 하드 코딩 됩니다.
hard-coded는 그 자체로 하나의 단어이므로 붙여쓰기를 해야 할 것 같습니다.
"하드 코딩" => "하드코딩"

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  먼저, 템플릿 중심의 폼을 살펴보고, 반응형 폼을 살펴봅시다.
전체적인 번역의 문체는 하십시오체(=합쇼체)를 기본으로 하고
명령형에 대해서는 하십시오체의 ~하십시오 또는 강제성을 순화하기 위해 해요체의 ~하세요.로 쓰고 있습니다.

"~시다"는 하오체의 청유형으로 전체적인 문체와 달라서 해요체로 수정 부탁 드립니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  [폼 요소](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML)를 컴포넌트의 템플릿에 가져다 놓습니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  초기 템플릿이 이미 방대해서 유효성 검사 메시지 `<divs>`를 추가하면 급격하게 지저분해질 것 입니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  사용자 입력에 대한 유효성 검사를 하는 것은, 당신이 [HTML 유효성 검사 속성](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation)을 요소에 추가하는 것 입니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  [커스텀 유효성 검사 지시자](#custom-validation)를 이 요리책에서 나중에 다룰 것 입니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  템플릿은 아주 천천히 선형적으로 자라나게 될 것 입니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  컴포넌트도 유효섬 검사 필드 당 한 라인, 유효성 검사 메시지당 한 라인의 비율로 선형적으로 자라나게 될 것 입니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  - `required`는 유효성 검사 목적으로 남긴 것이 아니라(코드에서 다룰 것 입니다.), css 스타일링과 접근성을 위해 남겼습니다.
의존 명사 '것'은 앞말과 띄어 적고, 서술격 조사 '이다'는 앞말에 붙여 적으므로, '~ 것입니다'와 같이 띄어쓰기합니다.
http://krdic.naver.com/rescript_detail.nhn?seq=6151
http://krdic.naver.com/rescript_detail.nhn?seq=7541

"것 입니다." => "것입니다."

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  사용자 입력에 대한 유효성 검사를 하는 것은, 당신이 [HTML 유효성 검사 속성](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation)을 요소에 추가하는 것 입니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  - `<input>` 요소는 HTML 유효성 검사 속성인 `required`와 `minlength`, `maxlength`를 가질 수 있습니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  - `<div>` 요소에 있는 `*ngIf`는 "name"에 오류가 있고 폼 컨트롤이 `dirty`나 `touched`일 때만 `<div>`들에 내포된 메시지를 보여줍니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  - 더 이상 이 요소에 대한 Angular 컨트롤를 참조할 필요가 없기 때문에 템플릿 변수 `#name`를 없엤습니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  `<input>` 요소는 거의 같습니다만, 주목할 만한 차이점이 있습니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  `<form>` 요소에서 템플릿 변수`#heroForm`을 설정하는 구성 요소 템플릿의 맨 위 부분을 살펴보십시오.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  핸들러로 전달된 `data` 객체는 현재 요소의 값을 가지고 있습니다.
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  템플릿 중심 접근법에서, 당신은 폼 요소와 유효성 검사 속성,
element는 "엘리먼트"로 번역하고 있습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    우리는 이 요리책의 모든 폼 템플릿의 밑에 있는 `SharedModule`이나 그것의 `SubmittedComponent`에 대해 이야기를 한적이 없습니다.
2017.03.24 slack에서 요리책을 쿡북으로 수정하기로 했습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  3번째 요리책 샘플은 히어로 폼을 _반응형 폼_ 스타일로 다시 작성했습니다..
2017.03.24 slack에서 요리책을 쿡북으로 수정하기로 했습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    그리고 요리책의 샘플에 있는 모든 파일과 비교해 봅시다.
2017.03.24 slack에서 요리책을 쿡북으로 수정하기로 했습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  이 요리책 샘플은 템플릿 중심과 반응형 폼 컨트롤에 적용된 커스텀 `forbiddenNamevalidator` 함수을 소개합니다.
2017.03.24 slack에서 요리책을 쿡북으로 수정하기로 했습니다.
https://github.com/angular/angular-ko/blob/master/ko-trans-guide.md

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  자, `HeroFormReactiveComponent`를 봅시다.
전체적인 번역의 문체는 하십시오체(=합쇼체)를 기본으로 하고
명령형에 대해서는 하십시오체의 ~하십시오 또는 강제성을 순화하기 위해 해요체의 ~하세요.로 쓰고 있습니다.

"~시다"는 하오체의 청유형으로 전체적인 문체와 달라서 해요체로 수정 부탁 드립니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> -  The template-driven approach relies on Angular to produce the control model and
공백이 별 의미는 없지만 가급적 원문은 그대로 유지 부탁 드립니다.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  템플릿 중심의 접근 방법은 컨트롤 모델 생산하고
위쪽에는 control model이 "제어모델"로 번역되었으나 여기서는 "컨트롤 모델"로 번역 되었습니다.
한 가지로 통일해주세요.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  `heroForm` 변수는 템플릿에서 Angular가 생성한 제어 모델에 대한 참조입니다.
control model이 "제어 모델", "제어모델", "컨트롤 모델"과 같이 여러가지로 번역되고 있습니다.
띄어쓰기를 포함하여 통일해주세요.

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  Angular는 HTML 유효성 검사 속성을 해석 할 수 있으며, 제어모델에 유효성 검사 기능을 추가 합니다.
"할"이 명사 뒤에 따라온다면 동사를 만드는 접미사가 되므로 붙여 써야합니다.
"해석 할 수" => "해석할 수"

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  - 입력 박스에 `"name"`이라는 `name` 속성을 부여함으로써, 그것과 연관된 `<input>`를  Angular의 내부 제어 모델에서 `name`이라는 폼 컨트롤과 연결 할 수 있습니다.
"할"이 명사 뒤에 따라온다면 동사를 만드는 접미사가 되므로 붙여 써야합니다.
"연결 할 수" => "연결할 수"

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  Angular는 더 이상 템플릿에서 컨트롤 모델을 가져 오지 않으므로 더 이상 탐색 할 수 없습니다.
"할"이 명사 뒤에 따라온다면 동사를 만드는 접미사가 되므로 붙여 써야합니다.
"탐색 할 수" => "탐색할 수"

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +  다른 곳에서는 "alice" 또는 구성하는 정규식이 일치하는 이름을 거부 할 수 있습니다.
"할"이 명사 뒤에 따라온다면 동사를 만드는 접미사가 되므로 붙여 써야합니다.
"거부 할 수" => "거부할 수"

2017-03-29 17:24 UTC, tiratano commented on public/docs/ts/latest/cookbook/form-validation.jade
> +    유효성 검사기 함수는 커스텀 폼 유효성 검사 챕터에서 자세히 다룹니다.
jade에서 \_ㅇㅇㅇ\_를 사용한 문법은 그 안의 것을 특별히 강조하기 위함입니다.
_forthcoming_이 번역하면 큰 의미는 없지만 원문에서는 특별히 강조까지 했던만큼
이런 경우는 가급적 원문의 강조 내용을 유지하는 것이 좋을 것입니다.

2017-03-30 01:23 UTC, grapgrap commented
리뷰 감사합니다. 빠른 시간 내에 수정해서 보내드리겠습니다

2017-04-06 15:11 UTC, closed without merging